name: tic_tac_toe
description: A beautiful Tic Tac Toe Game from scratch with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

module:
  androidX: true # Add this line.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true